// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ShowBill.Data;
using System;

namespace ShowBill.Data.Migrations
{
    [DbContext(typeof(ShowBillDataContext))]
    partial class ShowBillDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShowBill.Data.Concert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("Cost");

                    b.Property<int?>("DateId");

                    b.Property<string>("Descriprion");

                    b.Property<int?>("PlaceId");

                    b.Property<int>("Raiting");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("DateId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Concerts");
                });

            modelBuilder.Entity("ShowBill.Data.Date", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<int?>("MovieId");

                    b.Property<int?>("SportId");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("SportId");

                    b.ToTable("Dates");
                });

            modelBuilder.Entity("ShowBill.Data.Exhibition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("Cost");

                    b.Property<string>("Descriprion");

                    b.Property<DateTime>("EndDate");

                    b.Property<int?>("PlaceId");

                    b.Property<int>("Raiting");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Exhibitions");
                });

            modelBuilder.Entity("ShowBill.Data.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("Cost");

                    b.Property<string>("Descriprion");

                    b.Property<string>("Director");

                    b.Property<int?>("PlaceId");

                    b.Property<int>("Raiting");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("ShowBill.Data.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("Cost");

                    b.Property<string>("Descriprion");

                    b.Property<string>("Director");

                    b.Property<int?>("PlaceId");

                    b.Property<int>("Raiting");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("ShowBill.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MovieId");

                    b.Property<int?>("MovieId1");

                    b.Property<int?>("MovieId2");

                    b.Property<int?>("MovieId3");

                    b.Property<string>("Name");

                    b.Property<int?>("PerformanceId");

                    b.Property<int?>("PerformanceId1");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("MovieId1");

                    b.HasIndex("MovieId2");

                    b.HasIndex("MovieId3");

                    b.HasIndex("PerformanceId");

                    b.HasIndex("PerformanceId1");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("ShowBill.Data.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ConcertId");

                    b.Property<int?>("ExhibitionId");

                    b.Property<int?>("MovieId");

                    b.Property<int?>("PerformanceId");

                    b.Property<int?>("SportId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.HasIndex("ExhibitionId");

                    b.HasIndex("MovieId");

                    b.HasIndex("PerformanceId");

                    b.HasIndex("SportId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("ShowBill.Data.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("ShowBill.Data.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("Cost");

                    b.Property<string>("Descriprion");

                    b.Property<int?>("PlaceId");

                    b.Property<int>("Raiting");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Sport");
                });

            modelBuilder.Entity("ShowBill.Data.Concert", b =>
                {
                    b.HasOne("ShowBill.Data.Date", "Date")
                        .WithMany()
                        .HasForeignKey("DateId");

                    b.HasOne("ShowBill.Data.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("ShowBill.Data.Date", b =>
                {
                    b.HasOne("ShowBill.Data.Movie")
                        .WithMany("Dates")
                        .HasForeignKey("MovieId");

                    b.HasOne("ShowBill.Data.Sport")
                        .WithMany("Dates")
                        .HasForeignKey("SportId");
                });

            modelBuilder.Entity("ShowBill.Data.Exhibition", b =>
                {
                    b.HasOne("ShowBill.Data.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("ShowBill.Data.Movie", b =>
                {
                    b.HasOne("ShowBill.Data.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("ShowBill.Data.Performance", b =>
                {
                    b.HasOne("ShowBill.Data.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("ShowBill.Data.Person", b =>
                {
                    b.HasOne("ShowBill.Data.Movie")
                        .WithMany("Actors")
                        .HasForeignKey("MovieId");

                    b.HasOne("ShowBill.Data.Movie")
                        .WithMany("Composers")
                        .HasForeignKey("MovieId1");

                    b.HasOne("ShowBill.Data.Movie")
                        .WithMany("Producers")
                        .HasForeignKey("MovieId2");

                    b.HasOne("ShowBill.Data.Movie")
                        .WithMany("Screenwriters")
                        .HasForeignKey("MovieId3");

                    b.HasOne("ShowBill.Data.Performance")
                        .WithMany("Actors")
                        .HasForeignKey("PerformanceId");

                    b.HasOne("ShowBill.Data.Performance")
                        .WithMany("Autors")
                        .HasForeignKey("PerformanceId1");
                });

            modelBuilder.Entity("ShowBill.Data.Photo", b =>
                {
                    b.HasOne("ShowBill.Data.Concert")
                        .WithMany("Photos")
                        .HasForeignKey("ConcertId");

                    b.HasOne("ShowBill.Data.Exhibition")
                        .WithMany("Photos")
                        .HasForeignKey("ExhibitionId");

                    b.HasOne("ShowBill.Data.Movie")
                        .WithMany("Photos")
                        .HasForeignKey("MovieId");

                    b.HasOne("ShowBill.Data.Performance")
                        .WithMany("Photos")
                        .HasForeignKey("PerformanceId");

                    b.HasOne("ShowBill.Data.Sport")
                        .WithMany("Photos")
                        .HasForeignKey("SportId");
                });

            modelBuilder.Entity("ShowBill.Data.Sport", b =>
                {
                    b.HasOne("ShowBill.Data.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");
                });
#pragma warning restore 612, 618
        }
    }
}
